/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;

import heap.Heap;
import java.util.PriorityQueue;
import java.util.HashMap;

public class Huffman {
    public static void main(String[] args) {
        //variables
        HashMap<Character, Integer> frequencyTable = new HashMap<>();
        String text = "hello world";
        frequencyTable = initFrequencyTable(text);
        printFrequencies(frequencyTable);
    }

    public static void printFrequencies(HashMap map){
        System.out.println("Frequency Table:");
        System.out.println(map);
    }


    public static HashMap initFrequencyTable(String text) {
        StringBuilder result = new StringBuilder();
        HashMap<Character, Integer> frequencies = new HashMap<>();

        for (char c : text.toCharArray()) {
            // don't count spaces
            if (c != ' ') {
                //if key c has no instances, returns 0 instead of 'null'
                frequencies.put(c, frequencies.getOrDefault(c,0) + 1);
            }    
        }

        return frequencies;
    }
}

class Node {
    char character;
    int frequency;
    Node left;
    Node right;

    //constructor
    Node(char character, int frequency){
        this.character = character;
        this.frequency = frequency;
        left = null;
        right = null;
    }
}
