/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.PriorityQueue;
import java.util.HashMap;

public class HuffmanTest {
    @Test public void frequencyTable001() {
        String sampleTxt = "hello world";
        HashMap<Character, Integer> sampleTable = new HashMap<>();
        sampleTable.put('h',1);
        sampleTable.put('e',1);
        sampleTable.put('l',3);
        sampleTable.put('o',2);
        sampleTable.put('w',1);
        sampleTable.put('r',1);
        sampleTable.put('d',1);
        Huffman classBeingTested = new Huffman();
        HashMap<Character, Integer> tableTest = new HashMap();
        tableTest = classBeingTested.initFrequencyTable(sampleTxt);
        assertEquals(tableTest, sampleTable);
    }
    
}
