/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.PriorityQueue;
import java.util.HashMap;

public class HuffmanTest {
    @Test public void frequencyTable001() {
        //placeholder
    }
    
}
