/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;

import org.junit.Test;
import static org.junit.Assert.*;

public class HuffmanTest {
    @Test public void appHasAGreeting() {
        Huffman classUnderTest = new Huffman();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
